version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_management_app
    ports:
      - "8080:8080"
    depends_on:
      - db_user
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_user:5432/user_management_docker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - mynetwork

  db_user:
    image: postgres:13
    container_name: db_user
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=user_management_docker
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork: